"""Write the waitlist Worker next to the built site, configured from the project's files.

The deploy job (growth/jobs/deploy.py) uploads it as a preview version and promotes it after the
launch go. Cloudflare's free tier covers it: Workers 100,000 requests a day, D1 5 GB
and 100,000 writes a day, static assets free.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

from ..site.spec import load_pages
from ..util import write_atomic

HERE = Path(__file__).resolve().parent
MAIL_KINDS = ("confirm", "welcome", "movedup", "again")
PAGE_KINDS = ("confirm", "leave")


def worker_config(project: Any, ui: dict[str, dict[str, str]], languages: list[str] | None = None) -> dict[str, Any]:
    conf = project.raw["waitlist"]
    pages = load_pages(project)
    languages = languages or project.languages
    status_pages = {"player": pages[conf.get("status_page", "waitlist")]}
    status_pages["host"] = pages.get(str(conf.get("host_status_page", "")), status_pages["player"])
    role_pages = {"player": pages[project.site.get("home", "player")], "host": pages[project.site.get("host_home", "host")]}
    brand = str(project.brand["name"])

    def legal_url(lang: str) -> str:
        value = str(project.site.get("legal_notice", "") or "")
        if value in pages:
            spec = pages[value].langs.get(lang) or pages[value].langs[project.default_language]
            return project.site["base_url"] + spec.path
        return project.site["base_url"] + value if value else ""

    def strings(prefix: str, kinds: tuple[str, ...], parts: tuple[str, ...], optional_host: bool = False) -> dict[str, dict[str, str]]:
        out: dict[str, dict[str, str]] = {}
        for lang in languages:
            table = ui.get(lang, {})
            out[lang] = {}
            for kind in kinds:
                for part in parts:
                    key = f"{prefix}{kind}_{part}"
                    if key not in table:
                        raise KeyError(f"ui.toml [{lang}] is missing {key!r} (waitlist mails and pages)")
                    out[lang][f"{kind}_{part}"] = table[key].replace("{brand}", brand).replace("{legal_url}", legal_url(lang))
                    host_key = f"{prefix}host_{kind}_{part}"  # hosts may get their own wording
                    if optional_host and host_key in table:
                        out[lang][f"host_{kind}_{part}"] = table[host_key].replace("{brand}", brand).replace("{legal_url}", legal_url(lang))
        return out

    analytics = project.analytics if project.analytics.get("provider") == "posthog" else {}

    return {
        "brand": brand,
        "baseUrl": project.site["base_url"],
        "site": project.id,
        "wordmark": str(project.brand.get("wordmark", brand)),
        "languages": languages,
        "defaultLanguage": project.default_language,
        "home": {lang: spec.path for lang, spec in role_pages["player"].langs.items() if lang in languages},
        "paths": {
            "status": {
                role: {lang: spec.path for lang, spec in page.langs.items() if lang in languages} for role, page in status_pages.items()
            },
            "player": role_pages["player"].langs[project.default_language].path,
            "host": role_pages["host"].langs[project.default_language].path,
        },
        "rolePaths": {role: {lang: spec.path for lang, spec in page.langs.items() if lang in languages} for role, page in role_pages.items()},
        "moveUpPerReferral": int(conf.get("move_up_per_referral", 5)),
        "maxCreditedReferrals": int(conf.get("max_credited_referrals", 50)),
        "movedUpMail": bool(conf.get("moved_up_mail", True)),
        "counterMin": int(conf.get("counter_min", 0)),
        "signupsPerIpHour": int(conf.get("signups_per_ip_hour", 40)),
        "email": {"provider": str(conf.get("email_provider", "log")), "from": str(conf.get("email_from", ""))},
        "mail": strings("mail_", MAIL_KINDS, ("subject", "body"), optional_host=True),
        "pages": strings("action_", PAGE_KINDS, ("title", "text", "button")),
        # Cookieless analytics relay: the project key is a public write-only key, kept in the private home.
        "analytics": {"host": str(analytics.get("capture_host", "")), "key": str(analytics.get("project_api_key", ""))},
    }


def write_bundle(project: Any, ui: dict[str, dict[str, str]], out: Path, languages: list[str] | None = None) -> None:
    conf = project.raw["waitlist"]
    worker = out / "worker"
    worker.mkdir(parents=True, exist_ok=True)
    shutil.copy2(HERE / "waitlist.js", worker / "waitlist.js")
    shutil.copy2(HERE / "schema.sql", out / "schema.sql")
    config = json.dumps(worker_config(project, ui, languages), ensure_ascii=False, indent=2)
    write_atomic(worker / "config.js", f"// Generated by growth-engine from projects/{project.id}; do not edit.\nexport default {config};\n")
    write_atomic(
        worker / "index.js",
        'import { makeHandler } from "./waitlist.js";\nimport CONFIG from "./config.js";\n\n'
        "const handle = makeHandler(CONFIG);\n\nexport default { fetch: (request, env, ctx) => handle(request, env, ctx) };\n",
    )
    db_id = str(conf.get("d1_database_id", "")) or "SET-BY-deploy/cloudflare.sh"
    write_atomic(
        out / "wrangler.toml",
        f"""# Generated by growth-engine from projects/{project.id}; do not edit.
name = "{conf.get('worker_name', project.id + '-site')}"
main = "worker/index.js"
compatibility_date = "{conf.get('compatibility_date', '2026-09-01')}"
workers_dev = false
# Each uploaded version gets a private preview URL; the deploy job checks it before production.
preview_urls = true

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = ["/api/*", "/r/*"]

[[d1_databases]]
binding = "DB"
database_name = "{conf.get('database_name', project.id + '-waitlist')}"
database_id = "{db_id}"
""",
    )
    write_atomic(
        out / "DEPLOY.md",
        f"""# Deploying {project.name}

The engine's deploy job uploads this folder as a private preview version and checks it. Production
is only reached after the launch go (`[deploy] launched = true`), and rolls back on its own if the
live checks fail. Run it by hand with `growth deploy {project.id}`. See docs/deploy.md.
""",
    )
