"""Write the waitlist Worker next to the built site, configured from the project's files.

The result deploys with one `wrangler deploy` (deploy/cloudflare.sh wraps the one-time D1 and
secret setup around it). Cloudflare's free tier covers it: Workers 100,000 requests a day, D1 5 GB
and 100,000 writes a day, static assets free.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

from ..site.spec import load_pages
from ..util import write_atomic

HERE = Path(__file__).resolve().parent
MAIL_KINDS = ("confirm", "welcome", "movedup", "again")
PAGE_KINDS = ("confirm", "leave")


def worker_config(project: Any, ui: dict[str, dict[str, str]]) -> dict[str, Any]:
    conf = project.raw["waitlist"]
    pages = load_pages(project)
    status_page = pages[conf.get("status_page", "waitlist")]
    role_pages = {"player": pages[project.site.get("home", "player")], "host": pages[project.site.get("host_home", "host")]}
    brand = str(project.brand["name"])
    legal = str(project.site.get("legal_notice", ""))
    legal_url = project.site["base_url"] + legal if legal else ""

    def strings(prefix: str, kinds: tuple[str, ...], parts: tuple[str, ...]) -> dict[str, dict[str, str]]:
        out: dict[str, dict[str, str]] = {}
        for lang in project.languages:
            table = ui.get(lang, {})
            out[lang] = {}
            for kind in kinds:
                for part in parts:
                    key = f"{prefix}{kind}_{part}"
                    if key not in table:
                        raise KeyError(f"ui.toml [{lang}] is missing {key!r} (waitlist mails and pages)")
                    out[lang][f"{kind}_{part}"] = table[key].replace("{brand}", brand).replace("{legal_url}", legal_url)
        return out

    return {
        "brand": brand,
        "baseUrl": project.site["base_url"],
        "languages": project.languages,
        "defaultLanguage": project.default_language,
        "paths": {
            "status": {lang: spec.path for lang, spec in status_page.langs.items()},
            "player": role_pages["player"].langs[project.default_language].path,
            "host": role_pages["host"].langs[project.default_language].path,
        },
        "rolePaths": {role: {lang: spec.path for lang, spec in page.langs.items()} for role, page in role_pages.items()},
        "moveUpPerReferral": int(conf.get("move_up_per_referral", 5)),
        "maxCreditedReferrals": int(conf.get("max_credited_referrals", 50)),
        "movedUpMail": bool(conf.get("moved_up_mail", True)),
        "counterMin": int(conf.get("counter_min", 0)),
        "signupsPerIpHour": int(conf.get("signups_per_ip_hour", 5)),
        "email": {"provider": str(conf.get("email_provider", "log")), "from": str(conf.get("email_from", ""))},
        "mail": strings("mail_", MAIL_KINDS, ("subject", "body")),
        "pages": strings("action_", PAGE_KINDS, ("title", "text", "button")),
    }


def write_bundle(project: Any, ui: dict[str, dict[str, str]], out: Path) -> None:
    conf = project.raw["waitlist"]
    worker = out / "worker"
    worker.mkdir(parents=True, exist_ok=True)
    shutil.copy2(HERE / "waitlist.js", worker / "waitlist.js")
    shutil.copy2(HERE / "schema.sql", out / "schema.sql")
    config = json.dumps(worker_config(project, ui), ensure_ascii=False, indent=2)
    write_atomic(worker / "config.js", f"// Generated by growth-engine from projects/{project.id}; do not edit.\nexport default {config};\n")
    write_atomic(
        worker / "index.js",
        'import { makeHandler } from "./waitlist.js";\nimport CONFIG from "./config.js";\n\n'
        "const handle = makeHandler(CONFIG);\n\nexport default { fetch: (request, env, ctx) => handle(request, env, ctx) };\n",
    )
    db_id = str(conf.get("d1_database_id", "")) or "SET-BY-deploy/cloudflare.sh"
    write_atomic(
        out / "wrangler.toml",
        f"""# Generated by growth-engine from projects/{project.id}; do not edit.
name = "{conf.get('worker_name', project.id + '-site')}"
main = "worker/index.js"
compatibility_date = "{conf.get('compatibility_date', '2026-09-01')}"
workers_dev = false

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = ["/api/*", "/r/*"]

[[d1_databases]]
binding = "DB"
database_name = "{conf.get('database_name', project.id + '-waitlist')}"
database_id = "{db_id}"
""",
    )
    write_atomic(
        out / "DEPLOY.md",
        f"""# Deploying {project.name}

Nothing here is public until someone runs the deploy command.

    ./deploy/cloudflare.sh {project.id}

It builds the site, creates the D1 database on first use, applies schema.sql, checks the secrets
(EMAIL_API_KEY, STATS_TOKEN, HASH_SALT) and runs `wrangler deploy` from this folder.
See docs/deploy.md in the growth-engine repo.
""",
    )
